# Generated by Django 5.2 on 2025-05-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj03_models_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
